spring:
  datasource:
    url: jdbc:h2:file:~/data/boilerplate;NON_KEYWORDS=USER
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

springdoc:
  swagger-ui:
    path: /doc
    disable-swagger-default-url: true
